#!/usr/bin/env node
// Bundle non-TS assets the CLI ships at runtime, copied verbatim from the repo's
// single sources of truth so `skelm builder` can scaffold them into a generated
// project. Kept here (build step) rather than committed duplicates that drift:
// the build refreshes them, and guard tests assert the copies match canonical.
//
//   1. The canonical skelm authoring skill (`.agents/skills/skelm/SKILL.md`).
//   2. The shareable builder project files (`builder/*`) → `*.tmpl`. The root
//      `builder/` is the runnable, canonical instance; the scaffold ships these
//      verbatim. `tsconfig.json` and `package.json` are intentionally NOT derived
//      — the workspace-member builder extends `../tsconfig.base.json` and uses
//      `workspace:*` deps, while the scaffold needs a self-contained tsconfig
//      (`tsconfig.json.tmpl`, hand-maintained) and a version-injected package.json
//      (generated by makeBuilderPackageJson in src/builder.ts).
import { copyFileSync, mkdirSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = resolve(here, '..', '..', '..')

const skillSrc = join(repoRoot, '.agents', 'skills', 'skelm', 'SKILL.md')
const skillDestDir = join(here, '..', 'assets', 'skelm-skill')
mkdirSync(skillDestDir, { recursive: true })
copyFileSync(skillSrc, join(skillDestDir, 'SKILL.md'))
process.stdout.write(`copied skelm skill → ${join(skillDestDir, 'SKILL.md')}\n`)

const builderSrcDir = join(repoRoot, 'builder')
const builderDestDir = join(here, '..', 'assets', 'builder-template')
mkdirSync(builderDestDir, { recursive: true })
const BUILDER_FILES = [
  ['builder.workflow.mts', 'builder.workflow.mts.tmpl'],
  ['skelm.config.mts', 'skelm.config.mts.tmpl'],
  ['chatui-frontend.mts', 'chatui-frontend.mts.tmpl'],
  ['README.md', 'README.md.tmpl'],
  ['.gitignore', 'gitignore.tmpl'],
]
for (const [src, dest] of BUILDER_FILES) {
  copyFileSync(join(builderSrcDir, src), join(builderDestDir, dest))
  process.stdout.write(`copied builder asset → ${join(builderDestDir, dest)}\n`)
}
